### PR TITLE
Add Actual Budget to list of open source apps

### PR DESCRIPTION
**Pull request by gabeklavans**
Their support for SimpleFIN is currently [experimental](https://actualbudget.org/docs/experimental/simplefin-sync/). I will leave this as a draft PR as it gains traction, or if it's deemed ready enough to be advertised here.

### CODE REVIEW

**Comment by iffy** [comment]
Somehow I missed this. I'd be happy to add Actual Budget whenever you think it's ready.

**Comment by gabeklavans** [comment]
@matissjanis what do you think?

**Review by MatissJanis — APPROVED** [review]
SimpleFIN first-party support has been merged. It will be released with the next release (early October). LGTM!

**Comment by iffy** [comment]
Would it be okay to crop the Actual logo to just the rounded square? If not, I'll probably just use the logo as the title since the name is in there.

**Comment by iffy** [comment]
I merged the not cropped version. If you'd prefer the other, just let me know.

Thanks again for the PR!

**Pull request merged**
